### PR TITLE
Replace references to Chrome

### PR DESCRIPTION
**Pull request by Hirse**
I'm very happy that you make your extension available for both Chrome and Firefox. 
This PR changes "Zhongwen Chrome Extension" to "Zhongwen Browser Extension" and replaces links to the Chrome store with ones to GitHub.

### CODE REVIEW

**Comment by cschiller** [comment]
Right now the master branch is actually only for the Chrome releases. I'm doing the Firefox releases from the firefox branch. The code is currently the same, but it might diverge once Google moves to manifest V3 and service workers instead of background pages, so for the time being I think it's OK to have references to the Chrome extension in the master branch. But thanks for pointing this out, I'll try to clean it up in the near future.

**Comment by Hirse** [comment]
Fair enough. I didn't see the Firefox branch before.
Would it makes sense to you to have these changes on that branch instead?
I tried to keep them generic so it would work for either browser.

**Comment by cschiller** [comment]
Are there any other browsers besides Firefox that support installing from the Mozilla add-ons site? I'm asking because this is basically where the code from the firefox branch ends up.

**Comment by Hirse** [comment]
I know there are some Firefox related browsers (IceWeasel, SeaMonkey, etc), but I don't know if they can (or have to) get their add-ons from AMO (http://addons.mozilla.org).

**Comment by Hirse** [comment]
Closing this because there are already too many conflicts.

**Pull request closed without merging**
